### PR TITLE
Added option to reinstall rsudp if existing rsudp environment found

### PR DESCRIPTION
**Pull request by navneetercse**
Added a small case for reinstalling of rsudp environment, based on the user's choice for Unix-based machines in the unix-install-rsudp.sh file.

### CODE REVIEW

**Review by iannesbitt — CHANGES_REQUESTED** [review]
Thanks for this pull request! For user clarity, can you change line 54 to
```
    read -rp $'Press Enter to continue with update, or type reinstall and press Enter to reinstall...\n' update_choice
```

and line 56 to

```
    if [[ "$update_choice" == *"reinstall"* ]]; then
```

Thank you!

**Comment by iannesbitt** [comment]
Addresses issue raised in #44

**Comment by navneetercse** [comment]
> Thanks for this pull request! For user clarity, can you change line 54 to
> 
> ```
>     read -rp $'Press Enter to continue with update, or type reinstall and press Enter to reinstall...\n' update_choice
> ```
> 
> and line 56 to
> 
> ```
>     if [[ "$update_choice" == *"reinstall"* ]]; then
> ```
> 
> Thank you!

I have added the requested lines. Thank you!

**Review by iannesbitt — APPROVED** [review]
Looks good.

**Pull request merged**
